# .github/workflows/test.yml
name: Tests
on: [push, pull_request]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '9.0.x'

name: Run Tests
run: dotnet test --configuration Release --logger trx --results-directory TestResults

name: Publish Test Results
uses: dorny/test-reporter@v1
if: always()
with:
  name: Test Results
  path: TestResults/*.trx
  reporter: dotnet-trx